### PR TITLE
Change User<>Repo to be 1-Many. Add Repo creation ability. Add tests.

### PR DESCRIPTION
**Pull request by alexcouper**
I decided to change the User-Repo relationship on the basis that the many-to-many was a pre-optimization step. 

If the time comes that this needs to be changed then so be it.

### CODE REVIEW

**Comment by txels** [comment]
Yes totally agree

**Comment by txels** [comment]
Looks sane to me, although I have only skimmed through the code. Will take a decent look later this week.

**Comment by txels** [comment]
Travis is lying. We need to improve our test script.

**Comment by txels** [comment]
I did a quick fix to the test script so that Travis actually fails when tests fail.

**Comment by alexcouper** [comment]
Nice. I'll need to fix the version of flask to pre the removal of exceptions until flask restless releases an update.

The good news is that the fix in restless has been made so it wont be too long.

**Pull request closed without merging**
